function titleCase(value) {
  return value.replace(/\w\S*/g, (word) => word[0].toUpperCase() + word.slice(1).toLowerCase());
}

export function parsePrompt(prompt) {
  const lower = prompt.toLowerCase();
  const vertical = lower.includes('salon') ? 'salon' : lower.includes('real estate') ? 'real estate' : lower.includes('dental') ? 'dental clinic' : 'local business';
  const locationMatch = prompt.match(/(?:in|near|for)\s+([A-Z][A-Za-z\s-]{2,40}?)(?:,| with| sections|$)/);
  const location = locationMatch ? locationMatch[1].trim() : 'your city';
  const scheme = lower.includes('dark') ? 'dark' : lower.includes('pink') ? 'pink' : lower.includes('green') ? 'green' : 'blue';
  return { vertical, location, scheme, name: `Vexo ${titleCase(vertical)}` };
}

export function createReactFiles(prompt) {
  const spec = parsePrompt(prompt);
  const accent = spec.scheme === 'pink' ? '#ec4899' : spec.scheme === 'green' ? '#16a34a' : '#2563eb';
  const dark = spec.scheme === 'dark' ? '#07111f' : '#0f172a';
  const app = `const services = ['Premium consultation', 'Online booking', 'Before/after gallery', 'Fast follow-up'];
const root = document.getElementById('root');
root.innerHTML = \`<main>
  <section class="hero">
    <p class="eyebrow">${spec.location} • ${spec.vertical}</p>
    <h1>${spec.name} experiences built to convert visitors into booked clients.</h1>
    <p>Launch-ready one-page demo generated by Vexo Forge with services, proof, gallery, and contact capture.</p>
    <a class="button" href="#contact">Book a consultation</a>
  </section>
  <section class="grid">${'${services.map((service) => `<article><h2>${service}</h2><p>Clear copy, polished layout, and mobile-first calls to action for ' + spec.location + ' prospects.</p></article>`).join(\'\')}'}</section>
  <section><h2>Gallery</h2><div class="gallery"><span>Before</span><span>After</span><span>Client Story</span></div></section>
  <section id="contact" class="contact"><h2>Contact</h2><form><input placeholder="Name" /><input placeholder="Phone or email" /><textarea placeholder="What should we help with?"></textarea><button>Send enquiry</button></form></section>
</main>\`;`;
  return {
    'package.json': JSON.stringify({ type: 'module', scripts: { dev: 'node server.js', build: 'node --check src/main.js && node build.js', preview: 'node server.js' }, dependencies: {}, devDependencies: {} }, null, 2),
    'index.html': '<div id="root"></div><script type="module" src="/src/main.js"></script>',
    'build.js': "import { mkdirSync, copyFileSync, cpSync } from 'node:fs';\nmkdirSync('dist/src', { recursive: true });\ncopyFileSync('index.html', 'dist/index.html');\ncpSync('src', 'dist/src', { recursive: true });\nconsole.log('built dist/');\n",
    'server.js': "import http from 'node:http';\nimport { readFile } from 'node:fs/promises';\nimport { extname, join } from 'node:path';\nconst root = process.env.SERVE_ROOT || '.';\nconst port = Number(process.env.PORT || 5173);\nconst types = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' };\nhttp.createServer(async (req, res) => {\n  const url = req.url === '/' ? '/index.html' : req.url;\n  try { const file = await readFile(join(root, url)); res.writeHead(200, { 'content-type': types[extname(url)] || 'text/plain' }); res.end(file); }\n  catch { res.writeHead(404); res.end('Not found'); }\n}).listen(port, '0.0.0.0', () => console.log(`Preview listening on http://0.0.0.0:${port}`));\n",
    'src/main.js': app,
    'src/style.css': `:root{font-family:Inter,system-ui,sans-serif;color:white;background:${dark}}body{margin:0}main{max-width:1120px;margin:auto;padding:32px}.hero{padding:80px 24px;border-radius:32px;background:linear-gradient(135deg,${dark},${accent});box-shadow:0 24px 80px #0008}.eyebrow{text-transform:uppercase;letter-spacing:.18em;color:#bfdbfe}h1{font-size:clamp(2.4rem,7vw,5.5rem);line-height:.95;max-width:920px}.hero p{font-size:1.2rem;max-width:720px}.button,button{display:inline-block;background:white;color:${dark};padding:14px 22px;border-radius:999px;font-weight:800;border:0;text-decoration:none}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px;margin:32px 0}.grid article,.contact,.gallery span{background:#ffffff12;border:1px solid #ffffff22;border-radius:24px;padding:22px}.gallery{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:16px}.gallery span{min-height:120px;display:grid;place-items:center}form{display:grid;gap:12px}input,textarea{padding:14px;border-radius:14px;border:1px solid #ffffff33;background:#020617;color:white}textarea{min-height:120px}`
  };
}
